### ISSUE TITLE
Prototype new documentation layout/structure

### ISSUE THREAD

**Issue by meiqimichelle** [ipfs/ipfs-cluster-website#89]
This will be based on the v1 sitemap in #82 , and will iterate from there.

As as first step, I [forked the libp2p docs site](https://github.com/ipfs-cluster/docs). We can use this for rapid prototyping. (I expect the final layout to change, from a visual design perspective, quite a bit.)

Edit: [doc with @hsanjuan content topics is here](https://docs.google.com/document/d/1QG3k-xtb6En7sU_K-g76b_MzNqkYh13p7Uhu4_3TVIY/edit).

**Comment by pkafei** [comment]
### MVP Features

- [x] IPFS Cluster Header @meiqimichelle 
- [x] Delete Libp2p Branding  @meiqimichelle 
- [x] Move current pages to match[ draft sitemap architecture](https://github.com/ipfs/ipfs-cluster-website/issues/82) 
- [x] Create placeholders of new content (marked green in sitemap)
- [x] List of orphan content in README

**Comment by meiqimichelle** [comment]
Progress! Back over to you @pkafei for more content work 🎉 .

<img width="1329" alt="Screenshot 2019-06-05 22 45 43" src="https://user-images.githubusercontent.com/4827522/59009753-c9887500-87e3-11e9-8d48-3d49f557bf15.png">

**Comment by pkafei** [comment]
Sweet. This already looks so much better than before!

**Comment by pkafei** [comment]
### Next Steps:

- [x] Cleanup on content @meiqimichelle 
- [x] Cleanup on content @pkafei 
- [x] Show MVP to Adrian. @meiqimichelle 
- [x] Show MVP to Hector @pkafei

**Comment by meiqimichelle** [comment]
We now have the Cluster header on our MVP, and also a draft global nav that's based on our sitemap and the lovely setup at consul.io

<img width="1209" alt="Screenshot 2019-06-06 22 41 25" src="https://user-images.githubusercontent.com/4827522/59083459-5139b680-88ac-11e9-9557-d7edb523f722.png">

@pkafei once I started implementing the global nav, it became clear that our direction wasn't quite there yet in our first sitemap. Several of the items will likely move to the global nav (and then, once clicked on, will have their own 'docs-like' view), and what remains needs to be re-organized such that when someone clicks `DOCS`, they get a useful left nav. ie, you wouldn't want to click `DOCS` and then have another side nav section called `DEVELOPER DOCS` -- oops.

I tried to leave notes in the nav, and in the `_index.md` for each section so you could see where I'm at. If this is clear enough, please feel free to re-arrange the remaining `DOCS` sections and their children how you think they make sense (which may include bringing some children up to first-level nav).

Ever forward 💃

**Comment by lanzafame** [comment]
I had a quick look and I am really liking what I am seeing. A few comments (note some of this may not yet be in the MVP so if that is the case just ignore them):
- I would like there to be a homepage (from the sitemap I believe there will be but just confirming)
- Having the outline nav on the left as well as the 'prev page'/'next page' arrows seems like overkill
- I have a preference against having 'Architecture' as the first item in the outline nav, also to reference the consul.io docs again :) I find the connotation of having `internals>architecture` so it is clear that to use the software you do not need to understand this content or even know about it really but it is there if you need to dig deeper 
![1559889396](https://user-images.githubusercontent.com/5924712/59085596-7842c780-8942-11e9-97d7-e6adee75cbb5.png)
- Personally, I think `Upgrades` shouldn't be standalone, but should be an item under `Guides`

**Comment by pkafei** [comment]
I think I got the gist @meiqimichelle. Spent the day trying to wire the content and top nav portion of the website. The goal was to get the website to a state where if user clicks on the link `API` in the top nav they will only see documentation pertaining to the API. Here's what I've done so far:
https://github.com/ipfs-cluster/cluster-docs-mvp/tree/alt-nav

I think to get this to work, we need to create a  default directory and add a main template and use the main template logic in the nav section to properly go to the different content sections. 
https://gohugo.io/templates/menu-templates/#section-menu-for-lazy-bloggers
https://gohugo.io/content-management/sections/

**Comment by meiqimichelle** [comment]
I've made progress in what we talked about (ie, combining the docs template with a more flexible global nav). I ended up porting the MVP work into a branch in this repo because it made more sense to use our existing (well-structured) website as a base, and then add on the docs theme, rather than starting from the docs theme, which was never built to have a standard home page and global nav.

So! My latest work is in a branch called [new-docs-layout in this repo](https://github.com/ipfs/ipfs-cluster-website/tree/new-docs-layout). It looks like this at the moment (there's been some regression in the styles, but that's relatively straightforward to fix once the logic is working):
<img width="1272" alt="Screenshot 2019-06-10 21 08 36" src="https://user-images.githubusercontent.com/4827522/59243274-f19d1d00-8bc3-11e9-88ef-ab4338b98940.png">


The next steps, I believe, are:
- [x] to understand how [Hugo multiple menus work](https://gohugo.io/content-management/menus/), and separate what gets displayed in the global nav from what gets displayed in the side nav. @pkafei if you could focus on this during your day tomorrow, that would be A++ :D
- [x] pull the content changes we made in the MVP to this branch

**Comment by pkafei** [comment]
So when you click on the global nav you now only get the items related to that url on the side nav 



![](https://res.cloudinary.com/blockchain-side-hustle/image/upload/v1560272321/Screen_Shot_2019-06-11_at_6.55.37_PM_enwrae.png)

Realized today that Hugo uses a WHOLE lot of GO. Perusing through the GO documentation really helped me with understanding and implementing some of the logic implemented in Hugo's template tags.

https://gohugo.io/variables/menus/#menu-entry-variables
https://golang.org/doc/

Next steps:

- [x] Port sitemap content into new doc site
- [x] Get rid of parent nav in secondary navigation

**Comment by meiqimichelle** [comment]
Closer! There are still lots of bugs, but I think this is the right path, template-wise.

<img width="1090" alt="Screenshot 2019-06-11 23 09 49" src="https://user-images.githubusercontent.com/4827522/59327864-b1ab6800-8c9f-11e9-99c6-8f2ed46f2429.png">

<img width="1085" alt="Screenshot 2019-06-11 23 11 46" src="https://user-images.githubusercontent.com/4827522/59327869-b5d78580-8c9f-11e9-9832-a4e220a9585a.png">

**Here is what works:**
- the left nav accordion opens and closes the way you'd expect
- the menu is accessible! or, at least on its way there. (try tabbing and hitting 'enter' or 'space' to open and close the accordion items)
- styles are closer to the rest of site, and little triangle open/close isn't terrible
- link underline snazzy thing is working
- took advantage of "chapter" layout that came with the docs theme -- these are section landing pages, as seen in the screenshots
- latest content structure that we had going on the other MVP has been ported over here
- there's a 'homeless content' section under the main docs tab -- some of that info will get split into other pages

**Here is what needs to be looked at sooner rather than later -- @pkafei can you try for these tomorrow?**
- [x] P0: Another run at content -- actually try to split legacy content into new pages. This will make things easier to review for the rest of the team. _Edit: See @hsanjuan's breakdown in the doc linked from the next comment below for more input into how to structure content._
- [x] P2: Need nav in each section to persist -- currently depends on current page scope, needs to depend on top-level section, no matter how far into the page tree you go. @pkafei when you experiment with this one (or any other scripting/nav stuff), can you please make another branch off of mine? I'm not confident I'd be able to get back to where I was if I needed to ;) Thank you!

**For later, braindump -- these are less urgent to fix**
- [ ] ~Tabbed navigation jumps between nodes/sections, instead of going through every item (such as pages)~ _Edit: Moved to #92 . Turns out, none of our keyboard nav is working properly, not just the side nav. Something broader is going wrong._
- [x] Nested sections are rendering twice
- [x] Need an active class for a "you are here"

**Comment by meiqimichelle** [comment]
Met with @hsanjuan for an initial MVP review, we now have a doc with more content outline -- this one is ordered by importance as per @hsanjuan , and will help the team to the priority of what needs to be written/reviewed. Doc is [here](https://docs.google.com/document/d/1QG3k-xtb6En7sU_K-g76b_MzNqkYh13p7Uhu4_3TVIY/edit). Eventually, once the pages are relatively settled, we should move that content to an issue so we can check off sections/pages as they're reviewed/finished.

**Comment by meiqimichelle** [comment]
Fixed the nested-headings-rendering-twice issue. Turned out it is a [known bug](https://github.com/nico3333fr/jquery-accessible-accordion-aria/issues/31) in the accessible accordion module I adapted for our template. I implemented the author's suggested workaround for now, as my JavaScript isn't good enough to PR a proper fix to his code.

TADA :tada: -- only one 'components'
<img width="227" alt="Screenshot 2019-06-16 12 46 43" src="https://user-images.githubusercontent.com/4827522/59568843-d6079b80-9035-11e9-8987-65be903d8bb3.png">

**Comment by meiqimichelle** [comment]
I investigated the keyboard nav issue from a few comments up. Turns out, it is a broader issue. None of our keyboard nav is working properly. I've moved that work to #92 for later, and edited the comment above with that link.

**Comment by pkafei** [comment]
# Cluster Documentation Layout

## Introduction

### Overview 
- [x] Feature Set (legacy)
- [x] Introduction (legacy)

### Getting Started
- [x] Cluster Clients (what is `ipfs-cluster-service` and what is `ipfs-cluster-ctl`) #needs more detail
- [x] Pinning and Adding Content with `ipfs-cluster-ctl` (legacy and info taken from part of https://cluster.ipfs.io/documentation/internals/)
    * How to pin
    * How to unpin
    * How to pin with manual allocations
    * How to add content to cluster
    * How to check the status of a pin
    * Difference between pin "allocation" and pin "status"
    * How to recover a pin in error state
    * How to sync pin status to the ipfs daemon
- [x] CRDT vs Raft
- [x] Running Raft
    * Launching the first peer
    * Bootstrapping additional peers
    * Removing Peers
- [x] Running with CRDT
    * Launching (adding) and bootstrapping peers (will be much shorter than Raft), everything can be 
       explained in the same place
    * Trying it out: running `ipfs-cluster-peers ls` (how to check it your Cluster is up and running)  


## Guides 
- [x] Deploying on Docker and Kubernetes
- [x] Config settings and deployment
- [x] Ansible Playbook
- [x] Data Persistence and Recovery
- [x] Open Census Tracking and Metrics
- [x] Configuration setting for Cluster and IPFS (how is this different from production configuration settings under [Guides](https://docs.google.com/document/d/1QG3k-xtb6En7sU_K-g76b_MzNqkYh13p7Uhu4_3TVIY/edit)?)


## Architecture
- [x] Pubsub
- [x] Bitswap (intro, maybe links to libp2p and ipfs docs)
- [x] DHT
- [x] Gorpc
- [x] Ipfs-lite
- [x] Private networks

### Consensus Components
- [x] Raft
    * Elaborate on Raft
    * Elaborate on consensus
    * Explain the trust model
    * General operation

- [x] CRDT
    * Elaborate on CRDTs
    * Trust models ("Follower" mode, Trust model: trusting peers, untrusting) 

### Components
- [x] Main Component
- [x] Proxy API
- [x] REST API
- [x] IPFS Connector
- [x] Pin Tracker
- [x] Informer
- [x] Locator
- [x] State
- [x] Consensus 

## Overview of the APIs
- [x] API Intro- Explain both APIs, ctl can do everything the IPFS API can do
- [x] Rest API- Link to API Reference
- [x] IPFS Proxy API- Link to IPFS API reference
- [x] Clients
    * Go 
    * JavaScript 

## Security
- [x] RPC Authorization 
- [x] Setting Cluster Secret for RPC API

### How to Secure Your Cluster
- [x] Don't let unknown peers access your cluster
- [x] Secure the REST and Proxy API
- [x] Ports and Security
- [x] Backup and Disaster recovery


Notes: This outline is heavily influenced by [this doc](https://docs.google.com/document/d/1QG3k-xtb6En7sU_K-g76b_MzNqkYh13p7Uhu4_3TVIY/edit), and makes Guides into a first level section in the Documentation nav.

**Comment by meiqimichelle** [comment]
**The Latest:**
<img width="1292" alt="Screenshot 2019-07-25 21 17 35" src="https://user-images.githubusercontent.com/4827522/61925554-ac3d7080-af21-11e9-9c6d-55a34fef2701.png">


**Fixed in this version**
- [x] Search box and sidenav don't stick anymore; they scroll along with the rest of the page.
- [x] Sidenav displays the entire sidenav, no matter how deep you are in the docs
- [x] the sidenav accordions default to open so folks can see all their options at once, and get an idea of what's in the docs
- [x] Heading sizes/weight should be a bit more reasonable, with h1 as the largest/boldest, and the others falling in after (will loop back again later to refine)

**TO-DO**
- [x] The layout is broken at smaller-than-desktop sizes (was working before; removing the sticky sidenav broke them; should be relatively straightforward to fix) _-->moved to next comment_
- [x] Add 'active' class to sidenav
- [x] Improve sidenav styling and interactions. 
- [ ] See this article [Rules for Modern Navigation](https://www.uxbooth.com/articles/the-rules-for-modern-navigation/) for a nice checklist/overview of nav UX to review. Known todo: tab navigation and skip-to-nav link. _-->moved to next comment_
- [x] Remove accordions - I don't think they're adding much at this point 
- [x] Check the animation on the in-page anchor link scroll. May be annoying. (<-- need to find one to test on) _Edit: removed_
- [x] Remove sub-table-of-contents at the start of the breadcrumbs (maybe move it somewhere else, maybe just remove)
- [x] Change words in breadcrumbs from lower case to title case
- [x] General padding/alignment refinement (for example, the space between the sidenav and the main content should be a bit bigger; the search box and the breadcrumbs aren't aligned; there should be space between the breadcrumbs and the header; etc)
- [x] Check on syntax highlighting --> current behavior is [expected behavior for the syntax highlighting library that Hugo uses](https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages)
- [ ] Improve News section layout _-->moved to next comment_
- [x] Check on nav structure - where should `/guides/` live? _-->moved to next comment_

**Comment by meiqimichelle** [comment]
**The Latest on the branch `new-docs-layout`:**
<img width="1130" alt="Screenshot 2019-07-28 17 45 25" src="https://user-images.githubusercontent.com/4827522/62015340-88676e00-b15f-11e9-9d02-b6d17b1c4855.png">

**Next up on my list:**
- [x] Check on nav/content structure - where should `/guides/` live, for example?
- [x] The layout is broken at smaller-than-desktop sizes (was working before; removing the sticky sidenav broke them; should be relatively straightforward to fix)

**After that:**
- [ ] Improve News section layout
- [ ] See this article [Rules for Modern Navigation](https://www.uxbooth.com/articles/the-rules-for-modern-navigation/) for a nice checklist/overview of nav UX to review, check for any obvious gotchas. Known todo: enable tab navigation (doesn't seem to be working for any of our links) and skip-to-main hidden link

**Comment by meiqimichelle** [comment]
**And now we're here:**
<img width="1128" alt="Screenshot 2019-07-29 22 56 28" src="https://user-images.githubusercontent.com/4827522/62105960-c1cfd480-b258-11e9-91e2-33158a643fdf.png">

My latest work is on a branch called `content__mhz-edits`. See PR #96 for status.

**Comment by meiqimichelle** [comment]
**I can haz hamburger?**
<img width="400" alt="Screenshot 2019-07-30 22 15 55" src="https://user-images.githubusercontent.com/4827522/62185537-b55e8100-b317-11e9-8ae3-7e0b398e0e3e.png">
------------------------------------------------------------------------------
<img width="1150" alt="Screenshot 2019-07-30 22 16 09" src="https://user-images.githubusercontent.com/4827522/62185540-b7c0db00-b317-11e9-8309-d7c8be7a2f69.png">

**Comment by meiqimichelle** [comment]
v0 new docs layout has been live for a while. Closing. Can open other issues to troubleshoot.
